### ISSUE TITLE
Métodos que no hacen nada

### ISSUE THREAD

**Issue by PabloRai** [LosIsotopos/jrpg-2017a-cliente#6]
Mordisco de vida no hace nada

Robar vida y energía, solo roba energía

Aumentar defensa no aumenta nada

Aumentar evasión no aumenta nada

**Comment by NicolasSap** [comment]
**Robo de vida y energia**
Siendo [BEN]
roba 1 de salud a Guerrero Humano y al  Guerrero Orco y a Mago Humano
no roba al Asesino Orco, no roba al Asesino Elfo
Siendo [MAGOH]
roba 1 salud a Mago Elfo
**Aumentar Defensa**
Aumenta la defensa, pero no te pegan menos. Por ejemplo si sos Guerre Orco si usas Aumentar Defensa y despues Golpe Defensa, a media que usas aumentar aumenta el daño de esta habilidad.
